name: Bug Report
description: 유스티나 사용 중 발생한 버그나 오류를 제보합니다.
title: "[BUG] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: 문제 요약
      description: 발생한 문제 현상을 한 문장으로 명확하게 적어주세요.
      placeholder: 예) '/ctf profile' 명령어를 입력했으나 봇이 응답하지 않습니다.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      description: 개발팀이 문제를 똑같이 재현할 수 있도록 구체적인 순서를 적어주세요.
      placeholder: |
        1. '...' 채널로 이동한다.
        2. '/ctf ...' 명령어를 입력한다.
        3. 엔터를 눌렀을 때 오류가 발생한다.
    validations:
      required: true

  - type: textarea
    id: expected_actual
    attributes:
      label: 기대 동작 vs 실제 동작
      description: 원래 어떻게 되어야 하는지와, 실제로 어떻게 되었는지 비교해 주세요.
      placeholder: |
        - 기대: 프로필 정보가 임베드 메시지로 출력되어야 함.
        - 실제: "Unknown Error" 메시지만 출력됨.
    validations:
      required: true

  - type: input
    id: ctf_context
    attributes:
      label: CTF/서버 정보
      description: 문제가 발생한 환경(CTF 이름, 서버/채널 ID 등)을 알려주시면 디버깅에 도움이 됩니다.
      placeholder: 예) RubiyaLab CTF, Discord 서버 ID `1234...`, `#bot-cmd` 채널
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 스크린샷 또는 에러 로그
      description: 오류 화면 캡처나 로그가 있다면 붙여넣어 주세요. (민감 정보 제외)
      placeholder: 로그를 여기에 붙여넣어 주세요.
    validations:
      required: false