name: Feature Request
description: 새로운 기능이나 개선 사항을 제안해 주세요.
title: "[Feat] "
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: 제안 요약
      description: 제안하시는 기능을 한 문장으로 요약해 주세요.
      placeholder: 예) CTF 종료 시 자동으로 순위를 공지하는 기능이 필요합니다.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 관련된 문제점
      description: 이 기능이 왜 필요한가요? 현재 겪고 있는 불편함이나 문제를 설명해 주세요.
      placeholder: 예) 매번 수동으로 점수를 집계해서 공지하려니 시간이 너무 오래 걸립니다.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 원하는 기능 설명
      description: 구체적으로 어떤 기능이 추가되길 원하시나요?
      placeholder: |
         1. '/ctf ...' 명령어를 입력하면
         2. 현재 스코어보드를 이미지로 변환해서
         3. 지정된 채널에 자동으로 업로드했으면 좋겠습니다.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 이 기능을 구현하는 것 외에 고려해 본 다른 방법이 있나요?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: 기타 내용
      description: 스크린샷, 목업 이미지, 참고할 만한 레퍼런스가 있다면 첨부해 주세요.
    validations:
      required: false